spring:
  application:
    name: back
  datasource:
    url: jdbc:mysql://localhost:3306/your_car_your_way?allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
security:
  jwt:
    secret-key: ce47326acca5f5afbaba7077e26b7a468cab45a4d4e455f38fe5e07c714eeb83
    expiration-time: 86400000
server:
  port: 8080